[build]
  base = "Faculty-Excel-Converter"
  publish = "Faculty-Excel-Converter/frontend/build"
  command = "cd Faculty-Excel-Converter/frontend && npm install && npm run build"

[build.environment]
  NODE_VERSION = "20"

[dev]
  command = "npm run dev"
  targetPort = 3000
  port = 8888
  framework = "vite"
